/**
 * Per-agent sprite customization map.
 *
 * Maps each of the 26 Township agents to a Smallville body sprite plus:
 *
 *  - `customKey`  — a baked palette-swap sheet (generated by
 *    `scripts/mapgen/outfits.py` into `assets/characters/custom/`) that
 *    recolors the garment cluster only, replacing the old whole-body tint.
 *    When the texture is present it wins; `tint` remains as the runtime
 *    fallback for sheets the generator judged unreliable.
 *  - `accessoryKey` — a real pixel overlay spritesheet (generated by
 *    `scripts/mapgen/accessories.py` into `assets/characters/accessories/`),
 *    frame-aligned to the base sheet's head pixels, played frame-locked with
 *    the body (kippah / hijab / cap / hardhat / glasses).
 *  - `partner` — couple agents ("A & B" personas) render a REAL second body
 *    (its own spritesheet) that trails the lead by ~12px with a delayed
 *    follow and an offset walk phase. Partner bodies reuse sheets from other
 *    towns or the split folk sheets so the pair never twins visually.
 *
 * NOTE: the original Adam_Smith and Wolfgang_Schulz Smallville sheets are
 * cats-in-costume, not people — the rabbi and Tom Kowalski now map to human
 * bodies from the split `32x32folk.png` (folk-3 / folk-0).
 */

export interface SpriteCustomization {
  /** Phaser texture key of the base body (e.g., "char-Carlos_Gomez"). */
  spriteKey: string;
  /**
   * Baked palette-swap sheet key (e.g. "char-custom-miguel-hernandez" →
   * assets/characters/custom/miguel-hernandez_custom.png). Preferred over
   * `tint` when the texture loaded.
   */
  customKey?: string;
  /** Runtime multiplicative tint — fallback when no customKey sheet exists. */
  tint?: number;
  /** Accessory overlay key (e.g. "acc-hijab-Abigail_Chen"). */
  accessoryKey?: string;
  /** Couple partner: a real second body that trails the lead sprite. */
  partner?: {
    name: string;
    /** Partner body texture key. Falls back to the lead body + tint. */
    spriteKey?: string;
    tint?: number;
  };
}

/* ── Optional authored persona art overrides ───────────────── */
/*
 * Tint hints (fallback only — most agents now carry baked custom sheets):
 *   0xbcd4dc  cool teal-grey   — medical / scrubs implication
 *   0xd6ac82  warm tan         — labor / outdoor implication
 *   0xb8c0d8  cool blue-grey   — business / formal implication
 *   0xd9c2cc  mauve            — parent / cardigan implication
 *   0xc6d2b4  sage             — casual / community implication
 */

export const AGENT_CUSTOMIZATION: Record<string, SpriteCustomization> = {
  // ── Dover (6) ──────────────────────────────────────────────
  "carlos-restrepo":           { spriteKey: "char-Carlos_Gomez" },
  "miguel-hernandez":          {
    spriteKey: "char-Francisco_Lopez",
    customKey: "char-custom-miguel-hernandez",
    tint: 0xd6ac82,
    accessoryKey: "acc-hardhat-Francisco_Lopez",
  },
  "maria-santos":              {
    spriteKey: "char-Carmen_Ortiz",
    customKey: "char-custom-maria-santos",
    tint: 0xbcd4dc,
  },
  "esperanza-guzman":          { spriteKey: "char-Isabella_Rodriguez", tint: 0xc4b8a6 },
  "sofia-ramirez":             { spriteKey: "char-Jane_Moreno",      tint: 0xc6d2b4 },
  // folk-0: gray-haired man in a work shirt (Wolfgang_Schulz is a cat).
  "tom-kowalski":              { spriteKey: "char-folk-0",           tint: 0xd6cdb8 },

  // ── Montclair (7) ──────────────────────────────────────────
  "sarah-&-david-chen":        {
    spriteKey: "char-Mei_Lin",
    partner: { name: "David Chen", spriteKey: "char-Eddy_Lin" },
  },
  "rosa-chen":                 {
    spriteKey: "char-Yuriko_Yamamoto",
    customKey: "char-custom-rosa-chen",
    tint: 0xd1c8b0,
  },
  "jordan-williams":           {
    spriteKey: "char-Latoya_Williams",
    customKey: "char-custom-jordan-williams",
    tint: 0xc6d2b4,
  },
  "carmen-&-alejandro-vargas": {
    spriteKey: "char-Maria_Lopez",
    tint: 0xd9c2cc,
    partner: { name: "Alejandro Vargas", spriteKey: "char-Carlos_Gomez" },
  },
  // folk-3: distinguished white-haired man (Adam_Smith is a cat).
  "rabbi-daniel-goldstein":    {
    spriteKey: "char-folk-3",
    accessoryKey: "acc-kippah-folk-3",
  },
  "priya-patel":               { spriteKey: "char-Ayesha_Khan" },
  "margaret-\"peggy\"-o'brien":{
    spriteKey: "char-Hailey_Johnson",
    customKey: "char-custom-margaret-peggy-o-brien",
    tint: 0xb8a896,
  },

  // ── Parsippany (7) ─────────────────────────────────────────
  "raj-&-sunita-krishnamurthy":{
    spriteKey: "char-Rajiv_Patel",
    partner: { name: "Sunita Krishnamurthy", spriteKey: "char-Ayesha_Khan" },
  },
  "kantibhai-\"kanti\"-desai": { spriteKey: "char-Eddy_Lin",        tint: 0xc8b89c },
  "brian-mccarthy":            {
    spriteKey: "char-Sam_Moore",
    customKey: "char-custom-brian-mccarthy",
    tint: 0xb8c0d8,
  },
  "aisha-&-omar-khan":         {
    spriteKey: "char-Abigail_Chen",
    accessoryKey: "acc-hijab-Abigail_Chen",
    partner: { name: "Omar Khan", spriteKey: "char-folk-1" },
  },
  "pawan-sharma":              { spriteKey: "char-Giorgio_Rossi" },
  "linda-morrison":            {
    spriteKey: "char-Jennifer_Moore",
    customKey: "char-custom-linda-morrison",
    tint: 0xb8c0d8,
  },
  "grace-reyes":               { spriteKey: "char-Tamara_Taylor",   tint: 0xbcd4dc },

  // ── Randolph (6) ───────────────────────────────────────────
  "michael-\"mike\"-brennan":  {
    spriteKey: "char-Arthur_Burton",
    customKey: "char-custom-michael-mike-brennan",
    tint: 0xb8c0d8,
  },
  "jennifer-\"jen\"-russo":    {
    spriteKey: "char-Folk_Resident",
    customKey: "char-custom-jennifer-jen-russo",
    tint: 0xd9c2cc,
  },
  "frank-deluca":              {
    spriteKey: "char-Tom_Moreno",
    customKey: "char-custom-frank-deluca",
    tint: 0xa8a098,
    accessoryKey: "acc-cap-Tom_Moreno",
  },
  "tyler-&-megan-hart":        {
    spriteKey: "char-Ryan_Park",
    partner: { name: "Megan Hart", spriteKey: "char-folk-7" },
  },
  "vikram-iyer":               {
    spriteKey: "char-Klaus_Mueller",
    customKey: "char-custom-vikram-iyer",
    tint: 0x8aa0c8,
    accessoryKey: "acc-glasses-Klaus_Mueller",
  },
  "tony-mancini":              {
    spriteKey: "char-John_Lin",
    customKey: "char-custom-tony-mancini",
    tint: 0xd6ac82,
  },
};

/* ── Fallback ring (rotated when an agent isn't in the table) ── */

export const FALLBACK_SPRITES = [
  "char-Carlos_Gomez",
  "char-Maria_Lopez",
  "char-folk-3",
  "char-Abigail_Chen",
  "char-Tom_Moreno",
  "char-Hailey_Johnson",
  "char-Rajiv_Patel",
  "char-Tamara_Taylor",
];

/** Smallville sheets that are cats in costume, never residents. */
export const CAT_SHEETS: ReadonlySet<string> = new Set(["char-Adam_Smith", "char-Wolfgang_Schulz"]);

/**
 * Every human body sheet (the named Smallville set plus the split folk
 * sheets): the pool scenario-agnostic rosters and passers-by draw from.
 */
export const HUMAN_BODIES: string[] = [
  "char-Abigail_Chen", "char-Arthur_Burton", "char-Ayesha_Khan", "char-Carlos_Gomez",
  "char-Carmen_Ortiz", "char-Eddy_Lin", "char-Francisco_Lopez", "char-Giorgio_Rossi",
  "char-Hailey_Johnson", "char-Isabella_Rodriguez", "char-Jane_Moreno", "char-Jennifer_Moore",
  "char-John_Lin", "char-Klaus_Mueller", "char-Latoya_Williams", "char-Maria_Lopez",
  "char-Mei_Lin", "char-Rajiv_Patel", "char-Ryan_Park", "char-Sam_Moore", "char-Tamara_Taylor",
  "char-Tom_Moreno", "char-Yuriko_Yamamoto",
  "char-folk-0", "char-folk-1", "char-folk-2", "char-folk-3", "char-folk-4", "char-folk-5",
  "char-folk-6", "char-folk-7",
];

/** Mild, garment-safe tints (the documented hints above plus three neutrals). */
const MILD_TINTS = [0xd6ac82, 0xbcd4dc, 0xb8c0d8, 0xd9c2cc, 0xc6d2b4, 0xd1c8b0, 0xc4b8a6, 0xd6cdb8];

/** Neutral accessory overlays, keyed by the only body each is aligned to. */
const NEUTRAL_ACCESSORIES: Record<string, string> = {
  "char-Tom_Moreno": "acc-cap-Tom_Moreno",
  "char-Klaus_Mueller": "acc-glasses-Klaus_Mueller",
  "char-Francisco_Lopez": "acc-hardhat-Francisco_Lopez",
};

/** Distinct list of body texture keys to preload (base + partner bodies). */
export const ALL_CHARACTER_KEYS: string[] = Array.from(
  new Set([
    ...Object.values(AGENT_CUSTOMIZATION).map((c) => c.spriteKey),
    ...Object.values(AGENT_CUSTOMIZATION)
      .map((c) => c.partner?.spriteKey)
      .filter((k): k is string => !!k),
    ...FALLBACK_SPRITES,
    ...HUMAN_BODIES,
  ]),
);

/**
 * Baked palette-swap sheets to preload: texture key → path under
 * assets/characters/. Derived from customKey ("char-custom-{slug}" →
 * "custom/{slug}_custom.png").
 */
export const ALL_CUSTOM_SHEETS: Record<string, string> = Object.fromEntries(
  Object.values(AGENT_CUSTOMIZATION)
    .map((c) => c.customKey)
    .filter((k): k is string => !!k)
    .map((k) => [k, `custom/${k.slice("char-custom-".length)}_custom.png`]),
);

/**
 * Accessory overlay sheets to preload: texture key → path under
 * assets/characters/ ("acc-hijab-Abigail_Chen" →
 * "accessories/hijab-Abigail_Chen.png").
 */
export const ALL_ACCESSORY_SHEETS: Record<string, string> = Object.fromEntries(
  Object.values(AGENT_CUSTOMIZATION)
    .map((c) => c.accessoryKey)
    .filter((k): k is string => !!k)
    .map((k) => [k, `accessories/${k.slice("acc-".length)}.png`]),
);

/**
 * Look up an agent's authored sprite customization, falling back to a stable
 * generic body. The authored table belongs to the NJ-11 presentation; agent
 * ids are not globally namespaced, so another scenario may legitimately
 * reuse one without inheriting NJ-specific clothing, accessories, or couples.
 */
export function resolveAgentSprite(
  agentId: string,
  scenarioId?: string,
): SpriteCustomization {
  const direct = scenarioId === "nj11-2026" ? AGENT_CUSTOMIZATION[agentId] : undefined;
  if (direct) return direct;
  // A registered roster (see registerRosterArt) gives every resident of a
  // scenario a distinct body + mild tint; otherwise a stable hash picks a
  // generic body so reloads never reshuffle.
  const assigned = scenarioId ? rosterArt.get(scenarioId)?.[agentId] : undefined;
  if (assigned) return assigned;
  return { spriteKey: FALLBACK_SPRITES[hashId(agentId) % FALLBACK_SPRITES.length] };
}

function hashId(id: string): number {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;
  return h;
}

/* ── Scenario-agnostic outfits ─────────────────────────────── */

/**
 * Deterministic, collision-free art for a roster: ids sorted, each hashed
 * onto the human body pool and bumped past bodies already taken, with a
 * mild tint from the documented palette and a neutral accessory where one
 * is aligned to that body. The same roster always yields the same table,
 * so the canvas and the sidebar portraits agree.
 */
export function assignTownSprites(roster: string[]): Record<string, SpriteCustomization> {
  const ids = [...new Set(roster)].sort();
  const taken = new Set<string>();
  const out: Record<string, SpriteCustomization> = {};
  for (const id of ids) {
    const h = hashId(id);
    let idx = h % HUMAN_BODIES.length;
    // Bump past taken bodies; once every body is used, allow repeats but
    // vary the tint so twins still read apart.
    let tries = 0;
    while (taken.has(HUMAN_BODIES[idx]) && tries < HUMAN_BODIES.length) { idx = (idx + 1) % HUMAN_BODIES.length; tries++; }
    const spriteKey = HUMAN_BODIES[idx];
    const repeat = taken.has(spriteKey);
    taken.add(spriteKey);
    const tint = MILD_TINTS[((h >>> 8) + (repeat ? 3 : 0)) % MILD_TINTS.length];
    const accessory = NEUTRAL_ACCESSORIES[spriteKey];
    out[id] = {
      spriteKey,
      tint,
      ...(accessory && (h >>> 16) % 3 === 0 ? { accessoryKey: accessory } : {}),
    };
  }
  return out;
}

const rosterArt = new Map<string, Record<string, SpriteCustomization>>();
const rosterKeys = new Map<string, string>();

/**
 * Register a scenario's full roster once its ids are known (the socket
 * provider does this from simulation_started / the API roster). NJ-11
 * keeps its authored table; every other scenario gets `assignTownSprites`.
 * Idempotent for the same roster.
 */
export function registerRosterArt(scenarioId: string, roster: string[]): void {
  if (!scenarioId || scenarioId === "nj11-2026" || roster.length === 0) return;
  const key = [...new Set(roster)].sort().join("|");
  if (rosterKeys.get(scenarioId) === key) return;
  rosterArt.set(scenarioId, assignTownSprites(roster));
  rosterKeys.set(scenarioId, key);
}

/**
 * Body sheets for ambient passers-by: every human body not worn by one of
 * this town's residents (or their partners), so a stranger never twins a
 * neighbour. Falls back to the whole pool when a town uses everything.
 */
export function passerbyPool(scenarioId: string, residentIds: string[]): string[] {
  const worn = new Set<string>();
  for (const id of residentIds) {
    const c = resolveAgentSprite(id, scenarioId);
    worn.add(c.customKey ?? c.spriteKey);
    worn.add(c.spriteKey);
    if (c.partner?.spriteKey) worn.add(c.partner.spriteKey);
  }
  const pool = HUMAN_BODIES.filter((k) => !worn.has(k) && !CAT_SHEETS.has(k));
  return pool.length >= 2 ? pool : HUMAN_BODIES.filter((k) => !CAT_SHEETS.has(k));
}
